INSERT INTO public.plan_characteristics(
        id,
        model_plan_id,
        existing_model_or_new_track,
        existing_model,
        resembles_existing_model,
        existing_model_resemblance,
        how_model_resembles_note,
        how_model_differs_note,
        model_match__add_note,
        different_components,
        different_components_note,
        apm_qpp,
        apm_qpp_type,
        apm_qpp_note,
        model_key_characteristics,
        model_key_characteristics_other,
        model_key_characteristics_note,
        medicare_review_plan_bids,
        medicare_review_plan_bids_note,
        medicare_manage_enrollment,
        medicare_manage_enrollment_note,
        updated_plan_contact,
        updated_plan_contact_note,
        care_coordination_involved,
        care_coordination_involved_note,
        additional_services_involved,
        additional_services_involved_note,
        community_partners_involved,
        community_partners_involved_note,
        targeted_at_specific_geographies,
        geography_type,
        geography_type_other,
        geographies_applied_to,
        geographies_applied_to_other,
        targeted_at_specific_geographies_note,
        different_options_for_participation,
        different_options_for_participation_note,
        agreement_type,
        agreement_type_other,
        agreement_type_note,
        rule_making,
        rule_making_details,
        rule_making_note,
        authority_to_test,
        authority_to_test_other,
        authority_to_test_note,
        waivers_required,
        waiver_type,
        waiver_note,
        created_by,
        created_dts,
        modified_by,
        modified_dts,
        status
    ) (
        :id,
        :model_plan_id,
        NULLIF(:existing_model_or_new_track, ''),
        NULLIF(:existing_model, ''),
        NULLIF(:resembles_existing_model, ''),
        NULLIF(:existing_model_resemblance, ''),
        NULLIF(:how_model_resembles_note, ''),
        NULLIF(:how_model_differs_note, ''),
        NULLIF(:model_match__add_note, ''),
        NULLIF(:different_components, ''),
        NULLIF(:different_components_note, ''),
        NULLIF(:apm_qpp, ''),
        NULLIF(:apm_qpp_type, ''),
        NULLIF(:apm_qpp_note, ''),
        NULLIF(:model_key_characteristics, ''),
        NULLIF(:model_key_characteristics_other, ''),
        NULLIF(:model_key_characteristics_note, ''),
        NULLIF(:medicare_review_plan_bids, ''),
        NULLIF(:medicare_review_plan_bids_note, ''),
        NULLIF(:medicare_manage_enrollment, ''),
        NULLIF(:medicare_manage_enrollment_note, ''),
        NULLIF(:updated_plan_contact, ''),
        NULLIF(:updated_plan_contact_note, ''),
        NULLIF(:care_coordination_involved, ''),
        NULLIF(:care_coordination_involved_note, ''),
        NULLIF(:additional_services_involved, ''),
        NULLIF(:additional_services_involved_note, ''),
        NULLIF(:community_partners_involved, ''),
        NULLIF(:community_partners_involved_note, ''),
        NULLIF(:targeted_at_specific_geographies, ''),
        NULLIF(:geography_type, ''),
        NULLIF(:geography_type_other, ''),
        NULLIF(:geographies_applied_to, ''),
        NULLIF(:geographies_applied_to_other, ''),
        NULLIF(:targeted_at_specific_geographies_note, ''),
        NULLIF(:different_options_for_participation, ''),
        NULLIF(:different_options_for_participation_note, ''),
        NULLIF(:agreement_type, ''),
        NULLIF(:agreement_type_other, ''),
        NULLIF(:agreement_type_note, ''),
        NULLIF(:rule_making, ''),
        NULLIF(:rule_making_details, ''),
        NULLIF(:rule_making_note, ''),
        NULLIF(:authority_to_test, ''),
        NULLIF(:authority_to_test_other, ''),
        NULLIF(:authority_to_test_note, ''),
        NULLIF(:waivers_required, ''),
        NULLIF(:waiver_type, ''),
        NULLIF(:waiver_note, ''),
        NULLIF(:created_by, ''),
        NULLIF(:created_dts, ''),
        NULLIF(:modified_by, ''),
        NULLIF(:modified_dts, ''),
        NULLIF(:status, '')
    )
RETURNING id,
    model_plan_id,
    existing_model_or_new_track,
    existing_model,
    resembles_existing_model,
    existing_model_resemblance,
    how_model_resembles_note,
    how_model_differs_note,
    model_match__add_note,
    different_components,
    different_components_note,
    apm_qpp,
    apm_qpp_type,
    apm_qpp_note,
    model_key_characteristics,
    model_key_characteristics_other,
    model_key_characteristics_note,
    medicare_review_plan_bids,
    medicare_review_plan_bids_note,
    medicare_manage_enrollment,
    medicare_manage_enrollment_note,
    updated_plan_contact,
    updated_plan_contact_note,
    care_coordination_involved,
    care_coordination_involved_note,
    additional_services_involved,
    additional_services_involved_note,
    community_partners_involved,
    community_partners_involved_note,
    targeted_at_specific_geographies,
    geography_type,
    geography_type_other,
    geographies_applied_to,
    geographies_applied_to_other,
    targeted_at_specific_geographies_note,
    different_options_for_participation,
    different_options_for_participation_note,
    agreement_type,
    agreement_type_other,
    agreement_type_note,
    rule_making,
    rule_making_details,
    rule_making_note,
    authority_to_test,
    authority_to_test_other,
    authority_to_test_note,
    waivers_required,
    waiver_type,
    waiver_note,
    created_by,
    created_dts,
    modified_by,
    modified_dts,
    status;